USE FRETES;

DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(50) NULL,
  `SENHA` VARCHAR(50) NULL,
  `TIPO` VARCHAR(15) NULL,
  PRIMARY KEY (`ID_USUARIO`)
);

DROP TABLE IF EXISTS PRODUTO;
CREATE TABLE PRODUTO (
  `ID_PRODUTO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(50) NULL,
  `DESCRICAO` VARCHAR(200) NULL,
  `CLIENTE` VARCHAR(50) NULL,
  `STATUS` VARCHAR(10) NULL,
  `LOGRADOURO_ORIGEM` VARCHAR(100) NULL,
  `BAIRRO_ORIGEM` VARCHAR(100) NULL,
  `LOCALIDADE_ORIGEM` VARCHAR(100) NULL,
  `UF_ORIGEM` VARCHAR(2) NULL,
  `NUMERO_ORIGEM` VARCHAR(5) NULL,
  `COMPLEMENTO_ORIGEM` VARCHAR(25) NULL,
  `LOGRADOURO_DESTINO` VARCHAR(100) NULL,
  `BAIRRO_DESTINO` VARCHAR(100) NULL,
  `LOCALIDADE_DESTINO` VARCHAR(100) NULL,
  `UF_DESTINO` VARCHAR(2) NULL,
  `NUMERO_DESTINO` VARCHAR(5) NULL,
  `COMPLEMENTO_DESTINO` VARCHAR(25) NULL,
  PRIMARY KEY (`ID_PRODUTO`));
